sudo: required
services:
  - docker

before_install:
  - docker build -t gundalf72/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gundalf72/react-test npm test -- --coverage

after_success:
  - docker build -t gundalf72/multi-client ./client
  - docker build -t gundalf72/multi-nginx ./nginx
  - docker build -t gundalf72/multi-server ./server
  - docker build -t gundalf72/multi-worker ./worker

# Log in to the docker cli
# Add env variable - id DOCKER_ID and DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gundalf72/multi-client
  - docker push gundalf72/multi-nginx 
  - docker push gundalf72/multi-server
  - docker push gundalf72/multi-worker


# Take the images and push them to dockerhuv